[package]
name = "renegade_contracts"
version = "0.1.0"

[[target.starknet-contract]]
allowed-libfuncs-list = { name = "experimental" }
casm = true
casm-add-pythonic-hints = true

[dependencies]
starknet = "=2.0.1"
alexandria = { git = "https://github.com/keep-starknet-strange/alexandria", branch = "cairo-v2.0.1" }
